[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
 
[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200
 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200